pipeline {
    agent any
    
   tools {
    maven 'M2-HOME'
    jdk 'JAVA_HOME'
}

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/sinchanakumuda/SwagLabProject.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test -DsuiteXmlFile=crossBrowser.xml'
            }
        }

        stage('Publish Report') {
            steps {
                publishHTML(target: [
                    reportDir: 'AdvanceReports',
                    reportFiles: 'Extentreport*.html',
                    reportName: 'Extent Report'
                ])
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'AdvanceReports/*.html', fingerprint: true
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check reports for details.'
        }
    }
}
